### ISSUE TITLE
React typings of Cypher Editor instance

### ISSUE THREAD

**Issue by konsalex** [neo4j/cypher-editor#127]
### Description

Current editor's instance `ref` types are not correctly generated. 

The correct `ref` typings can help with advanced use cases, as an example uncontrolled state management or invoking actions, reflect how many lines we may have in the code-editor without explicit state management etc etc.

Added also an example where we may want to focus on the editor programmatically (for example using [Spotlighting](https://atlassian.design/components/onboarding/examples) for guides), and this can be done, but with TS complaining.

### Reproduce Steps

Check the Codesandbox [link here](https://codesandbox.io/p/sandbox/jovial-noyce-9gvwut?file=%2FREADME.md)

### Expected Behavior

Check the codesandbox link, what is logged in the console, versus what TS is complaining about.

### Current Behavior

Currently the ref types only include native class component methods, if not mistaken. 

### Additional Information

Discovered this issue when we needed to [integrate `CypherEditor` in Needle](https://github.com/neo4j/neo4j-design/pull/496) 🪡 

Also maybe adding arbitraty props, everything `HTMLDivElement` expects would be great, as then the editor would be able to accept `style` or `data-testid` etc etc as props.

**Comment by jharris4** [comment]
@konsalex #128 will add a new `style` prop to the react component, so if that gets merged you can use that to do the styling you were previously doing via a ref.

**Comment by OskarDamkjaer** [comment]
@konsalex Is there anything you require a ref to the component to do? What we do in query for the things you mention (programmatic focus & getting line counts is use the `onEditorCreated`) 

I rewrote your example to use it: https://codesandbox.io/p/sandbox/cyphereditor-ref-forked-z1z7ni?file=%2Fsrc%2FApp.tsx

**Comment by konsalex** [comment]
@OskarDamkjaer this could work in many cases, for us again it's not breaking and we have a workaround for our specific use case, it would just be better component design to surface the proper typings. Thanks for the example
