### ISSUE TITLE
Vs Code 

### ISSUE THREAD

**Issue by fnfbraga** [neo4j/cypher-editor#57]
Wouldn’t it be awesome to have this functionality straight in VS Code? I am willing to put some hours of work into it but honestly I don’t know the inner working of this lib and have never built a VS Code extension 🥴 

Mia it feasible to use this lib?

**Comment by oskarhane** [comment]
Yeah, that'd be very useful!
Check this out: https://neo4j.com/developer-blog/run-cypher-without-leaving-your-ide-with-neo4j-vscode-extension/

You'll find a VS Code extension in that post.
